import Head from 'next/head'
import Image from 'next/image'
import styles from '../../../styles/Subject.module.css'
import { useRouter } from 'next/router'
import QuestionCard from './question_card';

function get_questions() {

}

export default function Subject() {
    const router = useRouter();
    const { subject_name, board_level } = router.query;
    return (
        <div className={styles.container}>
            <Head>
                <title>{board_level + ' ' + subject_name}</title>
                <meta name='description' content='Generated by Saif the human' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>Subject page</h1>
                <br />
                <div className={styles.grid}>
                    {sample_questions.map(question => <QuestionCard q={question} />)}
                </div>
            </main>
        </div>
    );
}


// Temporary place holder questions until we link to api - Saif
var sample_questions = [
    {
        question_number:1,
        marks:10,
        is_MCQ:false,
        year:2020,
        component_region:13,
        exam_period:"June 2021",
        content:["First line of content", "Second line of content"],
        topics:["First topic", "Second topic", "Third topic"],
        options:["Yes", "No"],
        answer:["Maybe"]
    },

    {
        question_number:2,
        marks:10,
        is_MCQ:false,
        year:2020,
        component_region:13,
        exam_period:"June 2021",
        content:["First line of content", "Second line of content"],
        topics:["First topic", "Second topic", "Third topic"],
        options:["Yes", "No"],
        answer:["Maybe"]
    },

    {
        question_number:3,
        marks:10,
        is_MCQ:false,
        year:2020,
        component_region:13,
        exam_period:"June 2021",
        content:["First line of content", "Second line of content"],
        topics:["First topic", "Second topic", "Third topic"],
        options:["Yes", "No"],
        answer:["Maybe"]
    },

    {
        question_number:4,
        marks:10,
        is_MCQ:false,
        year:2020,
        component_region:13,
        exam_period:"June 2021",
        content:["First line of content", "Second line of content"],
        topics:["First topic", "Second topic", "Third topic"],
        options:["Yes", "No"],
        answer:["Maybe"]
    },

    {
        question_number:5,
        marks:10,
        is_MCQ:false,
        year:2020,
        component_region:13,
        exam_period:"June 2021",
        content:["First line of content", "Second line of content"],
        topics:["First topic", "Second topic", "Third topic"],
        options:["Yes", "No"],
        answer:["Maybe"]
    },
];